name: Build and Deploy

on:
  push:
    branches:
      - release/**
      - hotfix/**
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: tag
        default: unique-marketplace-backend
      is_latest:
        type: boolean
        description: also push latest tag
        default: false

jobs:
  build:
    name: Build and push Docker Image
    uses: UniqueNetwork/unique-marketplace-backend/.github/workflows/build-docker-image.yml@master
    secrets: inherit
    with:
      tag: unique-marketplace-backend
      dockerfile: ./Dockerfile
      is_latest: ${{ github.event.inputs.is_latest }}

  # todo: implement, just a placeholder for now
  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Deploying"
