name: Deploy to Develop cluster

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-gitlab-pipeline:
    name: Run gitlab pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gitlab
        run: |
          curl -X POST -F token=${{ secrets.UNIQUE_GITLAB_TOKEN }} -F ref=master -F variables[REMOTE_COMMIT]=${GITHUB_SHA} -F variables[DEPLOY_TO]=dev https://gitlab.uniquenetwork.dev/api/v4/projects/75/trigger/pipeline
  run-gitlab-pipeline-k8s:
    name: Run gitlab pipeline (k8s)
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gitlab
        run: |
          curl -X POST -F token=${{ secrets.UNIQUE_GITLAB_TOKEN_K8S }} -F ref=master -F variables[REMOTE_COMMIT]=${GITHUB_SHA} -F variables[DEPLOY_TO]=dev https://gitlab.uniquenetwork.dev/api/v4/projects/77/trigger/pipeline
